[general]
live_config_reload = false

[window]
padding = { x = 12, y = 20 }
decorations = "Buttonless"
opacity = 0.75
blur = true
option_as_alt = "Both"

[font]
normal = { family = "TX-02" }
size = 20

[colors.primary]
foreground = "#c0caf5"
background = "#1a1b26"

[colors.cursor]
text = "#1a1b26"
cursor = "#c0caf5"

[colors.selection]
text = "#c0caf5"
background = "#283457"

[colors.normal]
black = "#15161e"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"

[mouse]
hide_when_typing = true
